version: '3.8'
services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python api.py
    restart: always

  web-app:
    build: ./web-app
    ports:
      - "3000:3000"
    volumes:
      - ./web-app:/app
    command: npm start
    restart: always